services:
  mongodb:
    image: mongo:latest
    container_name: pokefinder_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./pf-backend
    container_name: pokefinder_backend
    volumes:
      - ./pf-backend:/app
      - /app/node_modules
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/pokefinder?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./pf-frontend
    container_name: pokefinder_frontend
    volumes:
      - ./pf-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend

volumes:
  mongo_data: